### ISSUE TITLE
views: fix and improve size checks on Lists

### ISSUE THREAD

**Issue by xabolcs** [openseedbox/openseedbox#111]
## Use `.size()` to get the size of the list (and use `.isEmpty()` if you aren't interested in exact values)

In #110 it was found that the (simplified (by commit 33b51527e57c19836c1fb05f04f2c8548a20fe34)) [job listing](https://github.com/openseedbox/openseedbox/blame/ae560a5a0aae2a6293f160a62931f37455c66e50/app/views/admin/jobs.html#L3) dies when the ORM is Ebean instead Siena.

### crash 01: no job runs
```java
@806koji7f
Internal Server Error (500) for request GET /admin/jobs

Template execution error (In /app/views/admin/jobs.html around line 3)
Execution error occurred in template /app/views/admin/jobs.html. Exception raised was GroovyRuntimeException : Cannot compare java.util.ArrayList with value '[]' and java.lang.Integer with value '0'.

play.exceptions.TemplateExecutionException: Cannot compare java.util.ArrayList with value '[]' and java.lang.Integer with value '0'
	at play.templates.BaseTemplate.throwException(BaseTemplate.java:83)
	at play.templates.GroovyTemplate.internalRender(GroovyTemplate.java:280)
	at play.templates.Template.render(Template.java:26)
	at play.templates.GroovyTemplate.render(GroovyTemplate.java:203)
	at play.mvc.results.RenderTemplate.<init>(RenderTemplate.java:28)
	at play.mvc.Controller.renderTemplate(Controller.java:836)
	at play.mvc.Controller.renderTemplate(Controller.java:814)
	at play.mvc.Controller.render(Controller.java:876)
	at controllers.Admin.jobs(Admin.java:258)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:536)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:473)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:467)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:436)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:159)
	at Invocation.HTTP Request(Play!)
Caused by: groovy.lang.GroovyRuntimeException: Cannot compare java.util.ArrayList with value '[]' and java.lang.Integer with value '0'
	at /app/views/admin/jobs.html.(line:3)
	at /app/views/admin/jobs.html.(line:60)
	at /app/views/admin/jobs.html.(line:58)
	at /app/views/admin/jobs.html.(line:65)
	at play.templates.GroovyTemplate.internalRender(GroovyTemplate.java:255)
	... 13 more
```

### crash 02: some job ran
```java
@806n9gok7
Internal Server Error (500) for request GET /admin/jobs

Template execution error (In /app/views/admin/jobs.html around line 3)
Execution error occurred in template /app/views/admin/jobs.html. Exception raised was MissingPropertyException : Exception evaluating property 'size' for com.avaje.ebean.common.BeanList, Reason: groovy.lang.MissingPropertyException: No such property: size for class: com.openseedbox.models.JobEvent Possible solutions: id.

play.exceptions.TemplateExecutionException: Exception evaluating property 'size' for com.avaje.ebean.common.BeanList, Reason: groovy.lang.MissingPropertyException: No such property: size for class: com.openseedbox.models.JobEvent
Possible solutions: id
	at play.templates.BaseTemplate.throwException(BaseTemplate.java:83)
	at play.templates.GroovyTemplate.internalRender(GroovyTemplate.java:280)
	at play.templates.Template.render(Template.java:26)
	at play.templates.GroovyTemplate.render(GroovyTemplate.java:203)
	at play.mvc.results.RenderTemplate.<init>(RenderTemplate.java:28)
	at play.mvc.Controller.renderTemplate(Controller.java:836)
	at play.mvc.Controller.renderTemplate(Controller.java:814)
	at play.mvc.Controller.render(Controller.java:876)
	at controllers.Admin.jobs(Admin.java:258)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:536)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:473)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:467)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:436)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:159)
	at Invocation.HTTP Request(Play!)
Caused by: groovy.lang.MissingPropertyException: Exception evaluating property 'size' for com.avaje.ebean.common.BeanList, Reason: groovy.lang.MissingPropertyException: No such property: size for class: com.openseedbox.models.JobEvent
Possible solutions: id
	at /app/views/admin/jobs.html.(line:3)
	at /app/views/admin/jobs.html.(line:60)
	at /app/views/admin/jobs.html.(line:58)
	at /app/views/admin/jobs.html.(line:65)
	at play.templates.GroovyTemplate.internalRender(GroovyTemplate.java:255)
	... 13 more
```
##  And the [answer](https://issues.apache.org/jira/browse/GROOVY-4094?focusedCommentId=14469045&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14469045) is: use `.size()` to get the size of the list

(Source: [GROOVY-4094: failures when resolving collection properties with the IBM jdk](https://issues.apache.org/jira/browse/GROOVY-4094))

This is no groovy issue. It is due to difference in implementation of ArrayList on Sun/IBM JVM. (and due to the fact that groovy allows access to private members, but that's a known issue)

On Sun JVM, the ArrayList class has a private property called size, that's why list.size returns you the value of that property.

On IBM JVM, the ArrayList class does not have any property called size, in that case groovy behavior is to apply the property on each member of the collection and collect values of all member.property in a collection and return. So, it now expects "size" property on each collection member, but that also fails because String class also does not have any size property.

If you are interested in getting the size of the list then list.size is not the groovy-way to get it anyway - it is list.size().

### Related StackOverflow Questions
* [Groovy has a size property for Collection?](https://stackoverflow.com/q/26532434)
* [Cannot compare java.util.ArrayList and java.lang.Integer](https://stackoverflow.com/q/24044788)

### Ebean uses `com.avaje.ebean.common.BeanList`, Siena uses `ArrayList`

In Siena items is an `ArrayList`. And looks like it was easy enough for Groovy to find [java.util.Collection.size()](https://docs.oracle.com/javase/8/docs/api/java/util/Collection.html#size--) from `.size`.

> id(class java.lang.String)=maintenance, data(class java.util.ArrayList)=[com.openseedbox.models.JobEvent@25, com.openseedbox.models.JobEvent@24] 

But in Ebean, its [com.avaje.ebean.common.BeanList](https://github.com/ebean-orm/ebean/blob/avaje-ebeanorm-8.1.1/src/main/java/com/avaje/ebean/common/BeanList.java) and Groovy is unable to deal with it. :disappointed:

> id(class java.lang.String)=maintenance, data(class com.avaje.ebean.common.BeanList)=[com.openseedbox.models.JobEvent@6, com.openseedbox.models.JobEvent@5]

### The views are full with direct access to that private `size` property

```sh
$ git grep -e '\.size' app/views/
app/views/account/invoices.html:#{if unpaid_invoices.size > 0}
app/views/account/invoices.html:#{if paid_invoices.size > 0}
app/views/admin/jobs.html:      #{if items?.size() > 0}
app/views/admin/jobs.html:      if (jobName.size != jobData.size || jobName.size == 0) {
app/views/admin/nodes.html:#{if (nodes.size() > 0)}
app/views/api/plans.html:#{if plans.size > 0}
app/views/client/index.html:#{if userMessages?.size > 0}
app/views/client/index.html:            #{if currentGroup == "Ungrouped" && groups.size == 1}
app/views/client/index.html:                                            #{if group == "Ungrouped" && groups.size == 1}
app/views/client/torrent-info.html:                             #{if (torrent.torrent.trackers.size > 0)}
app/views/client/torrent-info.html:                             #{if (torrent.torrent.peers.size > 0)}
app/views/client/torrent-list.html:             #{if torrentAddEvents.size > 0}
app/views/client/torrent-list.html:                     <h5><span class="text-success">Waiting to Add:</span> ${torrentAddEvents.size} torrent${torrentAddEvents.size.pluralize("s")}</h5>
app/views/client/torrent-list.html:             #{if torrentRemoveEvents.size > 0}
app/views/client/torrent-list.html:                     <h5><span class="text-error">Waiting to Remove:</span> ${torrentRemoveEvents.size} torrent${torrentRemoveEvents.size.pluralize("s")}</h5>
app/views/client/torrent-list.html:#{if torrents.size > 0}
app/views/tags/file-row.html:           #{if (_file.children.size() > 0)}
app/views/tags/file-row.html:#{if (_file.children.size > 0)}
```

**Comment by xabolcs** [comment]
> (and due to the fact that groovy allows access to private members, but that's a known issue)

```sh
$ git grep '\w\+\.\w\+' app/views| wc -l
408
```
