### ISSUE TITLE
Docker: shutdown OpenSeedbox gracefully

### ISSUE THREAD

**Issue by xabolcs** [openseedbox/openseedbox#80]
In containerized environment openseedbox-server has no time to stop the torrent backend:

```
$ time docker stop festive_chatelet 
festive_chatelet

real	0m1.822s
user	0m0.046s
sys	0m0.041s
```

And the logs:
```
transmission-daemon[83]: Transmission 2.94 (d8e60ee44f) started (session.c:740)
transmission-daemon[83]: RPC Server Adding address to whitelist: 127.0.0.1 (rpc-server.c:971)
transmission-daemon[83]: RPC Server Serving RPC and Web requests on port 127.0.0.1:1234/transmission/ (rpc-server.c:1213)
transmission-daemon[83]: RPC Server Whitelist enabled (rpc-server.c:1217)
transmission-daemon[83]: UDP Failed to set receive buffer: requested 4194304, got 425984 (tr-udp.c:84)
transmission-daemon[83]: UDP Please add the line "net.core.rmem_max = 4194304" to /etc/sysctl.conf (tr-udp.c:89)
transmission-daemon[83]: UDP Failed to set send buffer: requested 1048576, got 425984 (tr-udp.c:95)
transmission-daemon[83]: UDP Please add the line "net.core.wmem_max = 1048576" to /etc/sysctl.conf (tr-udp.c:100)
transmission-daemon[83]: DHT Reusing old id (tr-dht.c:307)
transmission-daemon[83]: DHT Bootstrapping from 108 IPv4 nodes (tr-dht.c:156)
transmission-daemon[83]: Using settings from "/media/openseedbox" (daemon.c:528)
transmission-daemon[83]: Saved "/media/openseedbox/settings.json" (variant.c:1274)
transmission-daemon[83]: Saved pidfile "/media/openseedbox/daemon.pid" (daemon.c:543)
transmission-daemon[83]: debian-edu-10.7.0-amd64-BD-1.iso Queued for verification (verify.c:269)
transmission-daemon[83]: Loaded 1 torrents (session.c:2034)
transmission-daemon[83]: debian-edu-10.7.0-amd64-BD-1.iso Verifying torrent (verify.c:224)
transmission-daemon[83]: Port Forwarding (NAT-PMP) initnatpmp succeeded (0) (natpmp.c:70)
transmission-daemon[83]: Port Forwarding (NAT-PMP) sendpublicaddressrequest succeeded (2) (natpmp.c:70)
transmission-daemon[83]: Port Forwarding State changed from "Not forwarded" to "Starting" (port-forwarding.c:92)
transmission-daemon[83]: Port Forwarding State changed from "Starting" to "???" (port-forwarding.c:92)
transmission-daemon[83]: Changed open file limit from 1048576 to 1024 (fdlimit.c:380)
transmission-daemon[83]: debian-edu-10.7.0-amd64-BD-1.iso Starting IPv4 DHT announce (poor, 9 nodes) (tr-dht.c:577)
2022-05-21 07:44:26,188 WARN received SIGTERM indicating exit request
2022-05-21 07:44:26,189 INFO waiting for nginx, openseedbox, supervisord-stopper to die
~        _            _ 
~  _ __ | | __ _ _  _| |
~ | '_ \| |/ _' | || |_|
~ |  __/|_|\____|\__ (_)
~ |_|            |__/   
~
~ play! 1.4.6, https://www.playframework.com
~
~ Ctrl+C to stop
~ 
~ using java version "11.0.15"
07:44:26,212 INFO  ~ Stopping backend because we started it!
2022-05-21 07:44:26,217 INFO stopped: openseedbox (exit status 0)
2022-05-21 07:44:26,222 INFO stopped: nginx (exit status 0)
2022-05-21 07:44:26,224 INFO stopped: supervisord-stopper (terminated by SIGTERM)
```

**Comment by xabolcs** [comment]
```patch
diff --git a/docker/run.sh b/docker/run.sh
index 391f777..2a677d0 100755
--- a/docker/run.sh
+++ b/docker/run.sh
@@ -42,4 +42,4 @@ if [ -z "$SYSFS_CGROUP_FILES" ]; then
        fi;
 fi;
 
-exec /play/play run -XshowSettings:vm
+$JAVA_HOME/bin/java -XshowSettings -cp $(/play/play cp --silent|grep '^\[.*\]$'|sed -e "s/', '/:/g;s/\['//;s/'\]//") -Dapplication.path=. play.server.Server
```

**Comment by xabolcs** [comment]
The hell is going on?
Just published `openseedbox/client` and `openseedbox/server` to Docker Hub, deployed it and got:
```
frontend_1      | 08:54:23,031 INFO  ~ Listening for HTTP on port 9000 ...
frontend_1      | 08:55:03,111 ERROR ~ 
frontend_1      | @7o545100a
frontend_1      | Error during job execution (com.openseedbox.jobs.NodePollerJob)
frontend_1      | Execution exception (In /app/com/openseedbox/jobs/LoggedJob.java around line 40)
frontend_1      | SienaException occurred : java.lang.IllegalAccessException: class siena.Util cannot access a member of class com.openseedbox.models.EventBase with modifiers "protected"
frontend_1      | play.exceptions.JavaExecutionException: java.lang.IllegalAccessException: class siena.Util cannot access a member of class com.openseedbox.models.EventBase with modifiers "protected"
frontend_1      | 	at play.jobs.Job.call(Job.java:225)
frontend_1      | 	at Invocation.Job(Play!)
frontend_1      | Caused by: siena.SienaException: java.lang.IllegalAccessException: class siena.Util cannot access a member of class com.openseedbox.models.EventBase with modifiers "protected"
frontend_1      | 	at siena.Util.readField(Util.java:310)
frontend_1      | 	at siena.jdbc.JdbcPersistenceManager.addParameters(JdbcPersistenceManager.java:370)
frontend_1      | 	at siena.jdbc.JdbcPersistenceManager.update(JdbcPersistenceManager.java:183)
frontend_1      | 	at siena.Model.update(Model.java:83)
frontend_1      | 	at com.openseedbox.jobs.LoggedJob.logResult(LoggedJob.java:40)
frontend_1      | 	at com.openseedbox.jobs.LoggedJob.runJob(LoggedJob.java:31)
frontend_1      | 	at com.openseedbox.jobs.GenericJob.doJobWithResult(GenericJob.java:15)
frontend_1      | 	at play.jobs.Job.call(Job.java:214)
frontend_1      | 	... 1 more
frontend_1      | Caused by: java.lang.IllegalAccessException: class siena.Util cannot access a member of class com.openseedbox.models.EventBase with modifiers "protected"
frontend_1      | 	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Unknown Source)
frontend_1      | 	at siena.Util.readField(Util.java:308)
frontend_1      | 	... 8 more
```

**Comment by xabolcs** [comment]
> The hell is going on?

`aarch64` and `amd64` were compiled natively, `armv7hf` was compiled with balena helper. Don't know what's happening. :disappointed:

**Comment by xabolcs** [comment]
> Recompiling `aarch64` with balena.

That helped. :shrug:

**Comment by xabolcs** [comment]
> Just published `openseedbox/client` and `openseedbox/serve`r with commit 70117beb9dd070aff147cad52b1ea0f9d645a4cc to Docker Hub ...

FYI: #85 is coming (without `STOPSIGNAL SIGQUIT`)! :slightly_smiling_face:

**Comment by gregorkistler** [comment]
> ```
> frontend_1      | 08:54:23,031 INFO  ~ Listening for HTTP on port 9000 ...
> frontend_1      | 08:55:03,111 ERROR ~ 
> frontend_1      | @7o545100a
> frontend_1      | Error during job execution (com.openseedbox.jobs.NodePollerJob)
> frontend_1      | Execution exception (In /app/com/openseedbox/jobs/LoggedJob.java around line 40)
> frontend_1      | SienaException occurred : java.lang.IllegalAccessException: class siena.Util cannot access a member of class com.openseedbox.models.EventBase with modifiers "protected"
> frontend_1      | play.exceptions.JavaExecutionException: java.lang.IllegalAccessException: class siena.Util cannot access a member of class com.openseedbox.models.EventBase with modifiers "protected"
> frontend_1      | 	at play.jobs.Job.call(Job.java:225)
> frontend_1      | 	at Invocation.Job(Play!)
> frontend_1      | Caused by: siena.SienaException: java.lang.IllegalAccessException: class siena.Util cannot access a member of class com.openseedbox.models.EventBase with modifiers "protected"
> frontend_1      | 	at siena.Util.readField(Util.java:310)
> frontend_1      | 	at siena.jdbc.JdbcPersistenceManager.addParameters(JdbcPersistenceManager.java:370)
> frontend_1      | 	at siena.jdbc.JdbcPersistenceManager.update(JdbcPersistenceManager.java:183)
> frontend_1      | 	at siena.Model.update(Model.java:83)
> frontend_1      | 	at com.openseedbox.jobs.LoggedJob.logResult(LoggedJob.java:40)
> frontend_1      | 	at com.openseedbox.jobs.LoggedJob.runJob(LoggedJob.java:31)
> frontend_1      | 	at com.openseedbox.jobs.GenericJob.doJobWithResult(GenericJob.java:15)
> frontend_1      | 	at play.jobs.Job.call(Job.java:214)
> frontend_1      | 	... 1 more
> frontend_1      | Caused by: java.lang.IllegalAccessException: class siena.Util cannot access a member of class com.openseedbox.models.EventBase with modifiers "protected"
> frontend_1      | 	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Unknown Source)
> frontend_1      | 	at siena.Util.readField(Util.java:308)
> frontend_1      | 	... 8 more
> ```

I rarely see this issue as well or this one:

```
09:05:21,585 ERROR ~ 

@7o546a4np
Error during job execution (com.openseedbox.jobs.NodePollerJob$NodePollerWorker)

Execution exception (In /app/com/openseedbox/models/JobEvent.java around line 22)
SienaException occurred : java.lang.IllegalAccessException: class siena.Util cannot access a member of class com.openseedbox.models.JobEvent with modifiers "private"

play.exceptions.JavaExecutionException: java.lang.IllegalAccessException: class siena.Util cannot access a member of class com.openseedbox.models.JobEvent with modifiers "private"
        at play.jobs.Job.call(Job.java:225)
        at play.jobs.Job$1.call(Job.java:119)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: siena.SienaException: java.lang.IllegalAccessException: class siena.Util cannot access a member of class com.openseedbox.models.JobEvent with modifiers "private"
        at siena.Util.readField(Util.java:310)
        at siena.jdbc.JdbcPersistenceManager.addParameters(JdbcPersistenceManager.java:370)
        at siena.jdbc.PostgresqlPersistenceManager.insertWithAutoIncrementKey(PostgresqlPersistenceManager.java:57)
        at siena.jdbc.JdbcPersistenceManager.insert(JdbcPersistenceManager.java:161)
        at siena.Model.insert(Model.java:79)
        at com.openseedbox.models.JobEvent.<init>(JobEvent.java:22)
        at com.openseedbox.jobs.LoggedJob.getJobEvent(LoggedJob.java:36)
        at com.openseedbox.jobs.LoggedJob.runJob(LoggedJob.java:15)
        at com.openseedbox.jobs.GenericJob.doJobWithResult(GenericJob.java:15)
        at play.jobs.Job.call(Job.java:214)
        ... 6 more
Caused by: java.lang.IllegalAccessException: class siena.Util cannot access a member of class com.openseedbox.models.JobEvent with modifiers "private"
        at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Unknown Source)
        at siena.Util.readField(Util.java:308)
        ... 15 more
```

Restarting the affected container usually fixes it. At least then I don't see it again until some weeks/months later.
Also the node poller job in the admin UI gets reported as 'Success' all the time even while having this error printed 🤷‍♂️

**Comment by xabolcs** [comment]
openseedbox/openseedbox-server@1c3d54d06210972ca551cb91f6ada30e18a8ffa7 landed, so here is a re-test:


```
$ docker run -ti --rm openseedbox/server
Unable to find image 'openseedbox/server:latest' locally
latest: Pulling from openseedbox/server
461246efe0a7: Already exists 
6c3131a5cac3: Already exists 
564566fab650: Already exists 
4f4fb700ef54: Already exists 
ae4ff6596c89: Already exists 
8197d1400c5b: Already exists 
306b5a85c897: Pull complete 
2e81fb62dd76: Pull complete 
7fe69a846eba: Pull complete 
Digest: sha256:039ed32e609cf00e4680e2959024c6fd8f40b0f2ae2f9bb196dabc71303c22fa
Status: Downloaded newer image for openseedbox/server:latest
Using CATALINA_BASE:   /tomcat
Using CATALINA_HOME:   /tomcat
Using CATALINA_TMPDIR: /tomcat/temp
Using JRE_HOME:        /java
Using CLASSPATH:       /tomcat/bin/bootstrap.jar:/tomcat/bin/tomcat-juli.jar
Using CATALINA_OPTS:   
NOTE: Picked up JDK_JAVA_OPTIONS:  --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
24-Jul-2022 17:41:02.319 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version name:   Apache Tomcat/10.1.0-M16
24-Jul-2022 17:41:02.324 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Jun 2 2022 09:33:00 UTC
24-Jul-2022 17:41:02.324 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version number: 10.1.0.0
24-Jul-2022 17:41:02.324 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
24-Jul-2022 17:41:02.324 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            5.13.0-1017-intel
24-Jul-2022 17:41:02.324 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
24-Jul-2022 17:41:02.324 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /java
24-Jul-2022 17:41:02.324 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           11.0.15+10
24-Jul-2022 17:41:02.325 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Eclipse Adoptium
24-Jul-2022 17:41:02.325 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /tomcat
24-Jul-2022 17:41:02.325 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /tomcat
24-Jul-2022 17:41:02.339 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.lang=ALL-UNNAMED
24-Jul-2022 17:41:02.339 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.io=ALL-UNNAMED
24-Jul-2022 17:41:02.339 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.util=ALL-UNNAMED
24-Jul-2022 17:41:02.340 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.util.concurrent=ALL-UNNAMED
24-Jul-2022 17:41:02.340 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
24-Jul-2022 17:41:02.340 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/tomcat/conf/logging.properties
24-Jul-2022 17:41:02.340 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
24-Jul-2022 17:41:02.340 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
24-Jul-2022 17:41:02.340 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
24-Jul-2022 17:41:02.341 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
24-Jul-2022 17:41:02.341 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/tomcat
24-Jul-2022 17:41:02.341 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/tomcat
24-Jul-2022 17:41:02.341 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/tomcat/temp
24-Jul-2022 17:41:02.348 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded Apache Tomcat Native library [1.2.33] using APR version [1.7.0].
24-Jul-2022 17:41:02.352 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized [OpenSSL 1.1.1n  15 Mar 2022]
24-Jul-2022 17:41:02.639 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
24-Jul-2022 17:41:02.668 INFO [main] org.apache.catalina.startup.Catalina.load Server initialization in [580] milliseconds
24-Jul-2022 17:41:02.711 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
24-Jul-2022 17:41:02.711 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/10.1.0-M16]
24-Jul-2022 17:41:02.728 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/tomcat/webapps/ROOT]
17:41:05,052 INFO  ~ Starting /tomcat/webapps/ROOT/WEB-INF/application
:: loading settings :: url = jar:file:/tomcat/webapps/ROOT/WEB-INF/lib/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
17:41:05,222 INFO  ~ Module openseedbox is available (/tomcat/webapps/ROOT/WEB-INF/application/modules/openseedbox-common)
17:41:05,329 INFO  ~ Application is precompiled
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/tomcat/webapps/ROOT/WEB-INF/lib/groovy-all-2.4.7.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
17:41:05,926 INFO  ~ Application 'openseedbox-server' is now started !
17:41:05,937 INFO  ~ Generating the secret key...
17:41:05,973 INFO  ~ Starting transmission-daemon via: transmission-daemon --config-dir /media/openseedbox --pid-file /media/openseedbox/daemon.pid 2>&1
24-Jul-2022 17:41:06.560 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/tomcat/webapps/ROOT] has finished in [3,831] ms
24-Jul-2022 17:41:06.564 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
24-Jul-2022 17:41:06.574 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [3905] milliseconds
transmission-daemon[43]: Transmission 3.00 (bb6b5a062e) started (session.c:769)
transmission-daemon[43]: RPC Server Adding address to whitelist: 127.0.0.1 (rpc-server.c:956)
transmission-daemon[43]: RPC Server Adding address to whitelist: ::1 (rpc-server.c:956)
transmission-daemon[43]: RPC Server Serving RPC and Web requests on 127.0.0.1:1234/transmission/ (rpc-server.c:1243)
transmission-daemon[43]: RPC Server Whitelist enabled (rpc-server.c:1249)
transmission-daemon[43]: UDP Failed to set receive buffer: requested 4194304, got 425984 (tr-udp.c:97)
transmission-daemon[43]: UDP Please add the line "net.core.rmem_max = 4194304" to /etc/sysctl.conf (tr-udp.c:99)
transmission-daemon[43]: UDP Failed to set send buffer: requested 1048576, got 425984 (tr-udp.c:105)
transmission-daemon[43]: UDP Please add the line "net.core.wmem_max = 1048576" to /etc/sysctl.conf (tr-udp.c:107)
transmission-daemon[43]: DHT Generating new id (tr-dht.c:389)
transmission-daemon[43]: Using settings from "/media/openseedbox" (daemon.c:646)
transmission-daemon[43]: Saved "/media/openseedbox/settings.json" (variant.c:1221)
transmission-daemon[43]: Saved pidfile "/media/openseedbox/daemon.pid" (daemon.c:662)
transmission-daemon[43]: Port Forwarding (NAT-PMP) initnatpmp succeeded (0) (natpmp.c:73)
transmission-daemon[43]: Port Forwarding (NAT-PMP) sendpublicaddressrequest succeeded (2) (natpmp.c:73)
transmission-daemon[43]: Port Forwarding State changed from "Not forwarded" to "Starting" (port-forwarding.c:106)
transmission-daemon[43]: Port Forwarding State changed from "Starting" to "???" (port-forwarding.c:106)
transmission-daemon[43]: DHT Attempting bootstrap from dht.transmissionbt.com (tr-dht.c:299)
^C24-Jul-2022 17:42:43.101 INFO [Thread-4] org.apache.coyote.AbstractProtocol.pause Pausing ProtocolHandler ["http-nio-8080"]
24-Jul-2022 17:42:43.109 INFO [Thread-4] org.apache.catalina.core.StandardService.stopInternal Stopping service [Catalina]
17:42:43,143 INFO  ~ Stopping backend because we started it!
transmission-daemon[43]: Saved "/media/openseedbox/settings.json" (variant.c:1221)
transmission-daemon[43]: DHT Not saving nodes, DHT not ready (tr-dht.c:445)
transmission-daemon[43]: Port Forwarding Stopped (port-forwarding.c:196)
transmission-daemon[43]: Closing session
24-Jul-2022 17:42:43.683 SEVERE [Thread-4] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [ROOT] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@5ba04028]) and a value of type [java.util.Stack] (value [[ROOT{}]]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
24-Jul-2022 17:42:43.687 SEVERE [Thread-4] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [ROOT] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@1fed2751]) and a value of type [java.util.Stack] (value [[org.apache.ivy.core.IvyContext@65b67d6b]]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
24-Jul-2022 17:42:43.710 INFO [Thread-4] org.apache.coyote.AbstractProtocol.stop Stopping ProtocolHandler ["http-nio-8080"]
24-Jul-2022 17:42:43.714 INFO [Thread-4] org.apache.coyote.AbstractProtocol.destroy Destroying ProtocolHandler ["http-nio-8080"]
```
