### ISSUE TITLE
Docker: openseedbox/tomcat didn't get the Apache Tomcat/10.1.0-M17 update through tomcat:10.1.0-jre11-temurin-focal

### ISSUE THREAD

**Issue by xabolcs** [openseedbox/openseedbox#93]
```
docker run --rm -ti --pull always tomcat:10.1.0-jre11-temurin-jammy
```
VS
```
docker run --rm -ti --pull always tomcat:10.1.0-jre11-temurin-focal
```

----

As previously noted (openseedbox/docker-base@0741bec61b8ce2430ac585d0a0cfad3184fc2de1), a downgrade to Focal Fossa was needed due to dependency naming:
```
Step 17/21 : RUN set -eux; 	apt-get update; 	xargs -rt apt-get install -y --no-install-recommends < "$TOMCAT_NATIVE_LIBDIR/.dependencies.txt"; 	apt-get install -y --no-install-recommends curl; 	rm -rf /var/lib/apt/lists/*
 ---> Running in ff7e6aa3d295
+ apt-get update
Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
Get:2 http://deb.debian.org/debian-security bullseye-security InRelease [48.4 kB]
Get:3 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
Get:4 http://deb.debian.org/debian bullseye/main arm64 Packages [8071 kB]
Get:5 http://deb.debian.org/debian-security bullseye-security/main arm64 Packages [180 kB]
Get:6 http://deb.debian.org/debian bullseye-updates/main arm64 Packages [2604 B]
Fetched 8462 kB in 2s (3500 kB/s)
Reading package lists...
+ xargs -rt apt-get install -y --no-install-recommends
apt-get install -y --no-install-recommends libapr1 libssl3 libuuid1
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libssl3
The command '/bin/sh -c set -eux; 	apt-get update; 	xargs -rt apt-get install -y --no-install-recommends < "$TOMCAT_NATIVE_LIBDIR/.dependencies.txt"; 	apt-get install -y --no-install-recommends curl; 	rm -rf /var/lib/apt/lists/*' returned a non-zero code: 123
```

**Comment by xabolcs** [comment]
Upgrading to Debian Bookwork increased the image by 20 MB, instantly. :roll_eyes: 

```
$ docker image ls openseedbox/tomcat:*
REPOSITORY           TAG          IMAGE ID       CREATED         SIZE
openseedbox/tomcat   dockerfile   640833589aea   2 minutes ago   168MB
openseedbox/tomcat   latest       007eabf05a1a   3 weeks ago     146MB
```

**Comment by xabolcs** [comment]
Meh.

So a simple `sed -e 's/^libssl3$/libssl1.1/' "$TOMCAT_NATIVE_LIBDIR/.dependencies.txt"` wouldn't help anyway?

**Comment by xabolcs** [comment]
```
Step 18/33 : RUN set -eux; 	nativeLines="$(catalina.sh configtest 2>&1)"; 	nativeLines="$(echo "$nativeLines" | grep 'Apache Tomcat Native')"; 	nativeLines="$(echo "$nativeLines" | sort -u)"; 	if ! echo "$nativeLines" | grep -E 'INFO: Loaded( APR based)? Apache Tomcat Native library' >&2; then 		echo >&2 "$nativeLines"; 		exit 1; 	fi
 ---> Running in a5a23ca87cb5
+ catalina.sh configtest
+ nativeLines=NOTE: Picked up JDK_JAVA_OPTIONS:  --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
Sep 12, 2022 12:50:59 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Server version name:   Apache Tomcat/10.1.0-M17
Sep 12, 2022 12:50:59 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Server built:          Jul 13 2022 18:51:03 UTC
Sep 12, 2022 12:50:59 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Server version number: 10.1.0.0
Sep 12, 2022 12:50:59 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: OS Name:               Linux
Sep 12, 2022 12:50:59 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: OS Version:            5.19.1-arm64
Sep 12, 2022 12:50:59 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Architecture:          aarch64
Sep 12, 2022 12:50:59 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Java Home:             /java
Sep 12, 2022 12:50:59 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: JVM Version:           11.0.16.1+1
Sep 12, 2022 12:50:59 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: JVM Vendor:            Eclipse Adoptium
Sep 12, 2022 12:50:59 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: CATALINA_BASE:         /tomcat
Sep 12, 2022 12:50:59 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: CATALINA_HOME:         /tomcat
Sep 12, 2022 12:50:59 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: --add-opens=java.base/java.lang=ALL-UNNAMED
Sep 12, 2022 12:50:59 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: --add-opens=java.base/java.io=ALL-UNNAMED
Sep 12, 2022 12:50:59 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: --add-opens=java.base/java.util=ALL-UNNAMED
Sep 12, 2022 12:50:59 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: --add-opens=java.base/java.util.concurrent=ALL-UNNAMED
Sep 12, 2022 12:50:59 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
Sep 12, 2022 12:50:59 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
Sep 12, 2022 12:50:59 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
Sep 12, 2022 12:50:59 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
Sep 12, 2022 12:50:59 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
Sep 12, 2022 12:50:59 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Dcatalina.base=/tomcat
Sep 12, 2022 12:50:59 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Dcatalina.home=/tomcat
Sep 12, 2022 12:50:59 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Djava.io.tmpdir=/tomcat/temp
Sep 12, 2022 12:50:59 PM org.apache.catalina.core.AprLifecycleListener init
WARNING: The Apache Tomcat Native library failed to load. The error reported was [/tomcat/native-jni-lib/libtcnative-2.so.0.0.1: libssl.so.3: cannot open shared object file: No such file or directory]
java.lang.UnsatisfiedLinkError: /tomcat/native-jni-lib/libtcnative-2.so.0.0.1: libssl.so.3: cannot open shared object file: No such file or directory
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(Unknown Source)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(Unknown Source)
	at java.base/java.lang.ClassLoader.loadLibrary0(Unknown Source)
	at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.base/java.lang.Runtime.loadLibrary0(Unknown Source)
	at java.base/java.lang.System.loadLibrary(Unknown Source)
	at org.apache.tomcat.jni.Library.<init>(Library.java:64)
	at org.apache.tomcat.jni.Library.initialize(Library.java:148)
	at org.apache.catalina.core.AprLifecycleListener.init(AprLifecycleListener.java:200)
	at org.apache.catalina.core.AprLifecycleListener.lifecycleEvent(AprLifecycleListener.java:138)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:135)
	at org.apache.catalina.startup.Catalina.load(Catalina.java:747)
	at org.apache.catalina.startup.Catalina.load(Catalina.java:769)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.catalina.startup.Bootstrap.load(Bootstrap.java:305)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:483)

Sep 12, 2022 12:51:00 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-nio-8080"]
Sep 12, 2022 12:51:00 PM org.apache.catalina.startup.Catalina load
INFO: Server initialization in [1903] milliseconds
+ echo NOTE: Picked up JDK_JAVA_OPTIONS:  --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
Sep 12, 2022 12:50:59 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Server version name:   Apache Tomcat/10.1.0-M17
Sep 12, 2022 12:50:59 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Server built:          Jul 13 2022 18:51:03 UTC
Sep 12, 2022 12:50:59 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Server version number: 10.1.0.0
Sep 12, 2022 12:50:59 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: OS Name:               Linux
Sep 12, 2022 12:50:59 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: OS Version:            5.19.1-arm64
Sep 12, 2022 12:50:59 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Architecture:          aarch64
Sep 12, 2022 12:50:59 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Java Home:             /java
Sep 12, 2022 12:50:59 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: JVM Version:           11.0.16.1+1
Sep 12, 2022 12:50:59 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: JVM Vendor:            Eclipse Adoptium
Sep 12, 2022 12:50:59 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: CATALINA_BASE:         /tomcat
Sep 12, 2022 12:50:59 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: CATALINA_HOME:         /tomcat
Sep 12, 2022 12:50:59 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: --add-opens=java.base/java.lang=ALL-UNNAMED
Sep 12, 2022 12:50:59 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: --add-opens=java.base/java.io=ALL-UNNAMED
Sep 12, 2022 12:50:59 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: --add-opens=java.base/java.util=ALL-UNNAMED
Sep 12, 2022 12:50:59 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: --add-opens=java.base/java.util.concurrent=ALL-UNNAMED
Sep 12, 2022 12:50:59 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
Sep 12, 2022 12:50:59 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
Sep 12, 2022 12:50:59 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
Sep 12, 2022 12:50:59 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
Sep 12, 2022 12:50:59 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
Sep 12, 2022 12:50:59 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Dcatalina.base=/tomcat
Sep 12, 2022 12:50:59 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Dcatalina.home=/tomcat
Sep 12, 2022 12:50:59 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Djava.io.tmpdir=/tomcat/temp
Sep 12, 2022 12:50:59 PM org.apache.catalina.core.AprLifecycleListener init
WARNING: The Apache Tomcat Native library failed to load. The error reported was [/tomcat/native-jni-lib/libtcnative-2.so.0.0.1: libssl.so.3: cannot open shared object file: No such file or directory]
java.lang.UnsatisfiedLinkError: /tomcat/native-jni-lib/libtcnative-2.so.0.0.1: libssl.so.3: cannot open shared object file: No such file or directory
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(Unknown Source)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(Unknown Source)
	at java.base/java.lang.ClassLoader.loadLibrary0(Unknown Source)
	at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.base/java.lang.Runtime.loadLibrary0(Unknown Source)
	at java.base/java.lang.System.loadLibrary(Unknown Source)
	at org.apache.tomcat.jni.Library.<init>(Library.java:64)
	at org.apache.tomcat.jni.Library.initialize(Library.java:148)
	at org.apache.catalina.core.AprLifecycleListener.init(AprLifecycleListener.java:200)
	at org.apache.catalina.core.AprLifecycleListener.lifecycleEvent(AprLifecycleListener.java:138)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:135)
	at org.apache.catalina.startup.Catalina.load(Catalina.java:747)
	at org.apache.catalina.startup.Catalina.load(Catalina.java:769)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.catalina.startup.Bootstrap.load(Bootstrap.java:305)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:483)

Sep 12, 2022 12:51:00 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-nio-8080"]
Sep 12, 2022 12:51:00 PM org.apache.catalina.startup.Catalina load
INFO: Server initialization in [1903] milliseconds
+ grep Apache Tomcat Native
+ nativeLines=WARNING: The Apache Tomcat Native library failed to load. The error reported was [/tomcat/native-jni-lib/libtcnative-2.so.0.0.1: libssl.so.3: cannot open shared object file: No such file or directory]
+ echo WARNING: The Apache Tomcat Native library failed to load. The error reported was [/tomcat/native-jni-lib/libtcnative-2.so.0.0.1: libssl.so.3: cannot open shared object file: No such file or directory]
+ sort -u
+ nativeLines=WARNING: The Apache Tomcat Native library failed to load. The error reported was [/tomcat/native-jni-lib/libtcnative-2.so.0.0.1: libssl.so.3: cannot open shared object file: No such file or directory]
+ echo WARNING: The Apache Tomcat Native library failed to load. The error reported was [/tomcat/native-jni-lib/libtcnative-2.so.0.0.1: libssl.so.3: cannot open shared object file: No such file or directory]
+ grep -E INFO: Loaded( APR based)? Apache Tomcat Native library
+ echo WARNING: The Apache Tomcat Native library failed to load. The error reported was [/tomcat/native-jni-lib/libtcnative-2.so.0.0.1: libssl.so.3: cannot open shared object file: No such file or directory]
WARNING: The Apache Tomcat Native library failed to load. The error reported was [/tomcat/native-jni-lib/libtcnative-2.so.0.0.1: libssl.so.3: cannot open shared object file: No such file or directory]
+ exit 1
The command '/bin/sh -c set -eux; 	nativeLines="$(catalina.sh configtest 2>&1)"; 	nativeLines="$(echo "$nativeLines" | grep 'Apache Tomcat Native')"; 	nativeLines="$(echo "$nativeLines" | sort -u)"; 	if ! echo "$nativeLines" | grep -E 'INFO: Loaded( APR based)? Apache Tomcat Native library' >&2; then 		echo >&2 "$nativeLines"; 		exit 1; 	fi' returned a non-zero code: 1
```

**Comment by xabolcs** [comment]
I'll solve this problem by dropping OpenSSL support ...: the published versions should be used behind a reverse proxy anyway.

```
$ docker images openseedbox/tomcat:*
REPOSITORY           TAG          IMAGE ID       CREATED              SIZE
openseedbox/tomcat   dockerfile   c2658a937167   About a minute ago   153MB
openseedbox/tomcat   latest       2c20df3ec457   2 months ago         156MB
```

```
$ docker run --rm -ti openseedbox/tomcat:dockerfile 
Using CATALINA_BASE:   /tomcat
Using CATALINA_HOME:   /tomcat
Using CATALINA_TMPDIR: /tomcat/temp
Using JRE_HOME:        /java
Using CLASSPATH:       /tomcat/bin/bootstrap.jar:/tomcat/bin/tomcat-juli.jar
Using CATALINA_OPTS:   
NOTE: Picked up JDK_JAVA_OPTIONS:  --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
30-Oct-2022 14:30:11.028 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version name:   Apache Tomcat/10.1.1
30-Oct-2022 14:30:11.032 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Oct 3 2022 12:42:14 UTC
30-Oct-2022 14:30:11.032 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version number: 10.1.1.0
30-Oct-2022 14:30:11.032 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
30-Oct-2022 14:30:11.032 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            5.15.0-1016-intel-iotg
30-Oct-2022 14:30:11.032 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
30-Oct-2022 14:30:11.032 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /java
30-Oct-2022 14:30:11.033 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           11.0.16.1+1
30-Oct-2022 14:30:11.033 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Eclipse Adoptium
30-Oct-2022 14:30:11.033 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /tomcat
30-Oct-2022 14:30:11.033 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /tomcat
30-Oct-2022 14:30:11.046 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.lang=ALL-UNNAMED
30-Oct-2022 14:30:11.046 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.io=ALL-UNNAMED
30-Oct-2022 14:30:11.046 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.util=ALL-UNNAMED
30-Oct-2022 14:30:11.047 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.util.concurrent=ALL-UNNAMED
30-Oct-2022 14:30:11.047 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
30-Oct-2022 14:30:11.047 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/tomcat/conf/logging.properties
30-Oct-2022 14:30:11.047 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
30-Oct-2022 14:30:11.047 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
30-Oct-2022 14:30:11.047 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
30-Oct-2022 14:30:11.048 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
30-Oct-2022 14:30:11.048 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/tomcat
30-Oct-2022 14:30:11.048 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/tomcat
30-Oct-2022 14:30:11.048 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/tomcat/temp
30-Oct-2022 14:30:11.050 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent The Apache Tomcat Native library which allows using OpenSSL was not found on the java.library.path: [/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib]
30-Oct-2022 14:30:11.337 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
30-Oct-2022 14:30:11.368 INFO [main] org.apache.catalina.startup.Catalina.load Server initialization in [513] milliseconds
30-Oct-2022 14:30:11.411 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
30-Oct-2022 14:30:11.411 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/10.1.1]
30-Oct-2022 14:30:11.432 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
30-Oct-2022 14:30:11.448 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [79] milliseconds
```

**Comment by xabolcs** [comment]
I know kung-fu:

```
root@886e9e280ed6:/usr/local/tomcat# xq -x 'try((.Server.Listener[]|select(."@className"=="org.apache.catalina.core.AprLifecycleListener")."@SSLEngine")="off") // .' conf/server.xml 
<Server port="8005" shutdown="SHUTDOWN">
  <Listener className="org.apache.catalina.startup.VersionLoggerListener"></Listener>
  <Listener className="org.apache.catalina.core.AprLifecycleListener" SSLEngine="off"></Listener>
  <Listener className="org.apache.catalina.core.JreMemoryLeakPreventionListener"></Listener>
  <Listener className="org.apache.catalina.mbeans.GlobalResourcesLifecycleListener"></Listener>
  <Listener className="org.apache.catalina.core.ThreadLocalLeakPreventionListener"></Listener>
  <GlobalNamingResources>
    <Resource name="UserDatabase" auth="Container" type="org.apache.catalina.UserDatabase" description="User database that can be updated and saved" factory="org.apache.catalina.users.MemoryUserDatabaseFactory" pathname="conf/tomcat-users.xml"></Resource>
  </GlobalNamingResources>
  <Service name="Catalina">
    <Connector port="8080" protocol="HTTP/1.1" connectionTimeout="20000" redirectPort="8443"></Connector>
    <Engine name="Catalina" defaultHost="localhost">
      <Realm className="org.apache.catalina.realm.LockOutRealm">
        <Realm className="org.apache.catalina.realm.UserDatabaseRealm" resourceName="UserDatabase"></Realm>
      </Realm>
      <Host name="localhost" appBase="webapps" unpackWARs="true" autoDeploy="true">
        <Valve className="org.apache.catalina.valves.AccessLogValve" directory="logs" prefix="localhost_access_log" suffix=".txt" pattern='%h %l %u %t "%r" %s %b'></Valve>
      </Host>
    </Engine>
  </Service>
</Server>
```

While the above `SSLEngine="on"` -> `"off"` change doesn't work, I'll rework commit openseedbox/docker-base@331de53820757881ece63c0184d4fe1d29ebaf75:
```
Nov 23, 2022 5:08:25 PM org.apache.catalina.core.AprLifecycleListener init
SEVERE: [off] is not a valid value for SSLEngine when using version [2.0.1] of the Tomcat Native library since SSL is required for version 2.x onwards.
```

**Comment by gregorkistler** [comment]
> ```
> Nov 23, 2022 5:08:25 PM org.apache.catalina.core.AprLifecycleListener init
> SEVERE: [off] is not a valid value for SSLEngine when using version [2.0.1] of the Tomcat Native library since SSL is required for version 2.x onwards.
> ```

Mhhh, wonder why it complains about `off` as it is still a valid value according to the [documentation](https://tomcat.apache.org/tomcat-10.1-doc/config/listeners.html):


> Name of the SSLEngine to use. off: do not use SSL, on: use SSL but no specific ENGINE.
> 
> The default value is on. This initializes the native SSL engine, which must be enabled in the APR/native connector by the use of the SSLEnabled attribute.
> 
> See the [Official OpenSSL website](http://www.openssl.org/) for more details on supported SSL hardware engines and manufacturers.
> 
> Tomcat Native 2.x onwards requires SSL so if SSLEngine is set to off when using Tomcat Native 2.x onwards, the APR/native library will be disabled.

In order to get rid of the log message 
```
[main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent The Apache Tomcat Native library which allows using OpenSSL was not found on the java.library.path: [/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib]
```

I've simply deleted the according line 27 in the `conf/server.xml` so the `AprLifecycleListener` won't be enabled in first place.

**Comment by xabolcs** [comment]
> I've simply deleted the according line 28 in the `conf/server.xml` so the `AprLifecycleListener` won't be enabled in first place.

Yup, I will do the same but with `xq`! :+1: :grinning:

**Comment by xabolcs** [comment]
`openseedbox/server` and `openseedbox/client` images are fresh and based on Apache Tomcat 10.1.2! :+1:
